spring:
  data:
    mongodb:
      username: admin
      password: tw2020
      database: admin
      host: ec2-161-189-97-207.cn-northwest-1.compute.amazonaws.com.cn
      port: 9002
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        exclude: env,beans
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    shutdown:
      enabled: true
