spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leanengine
    username: root
  jpa:
    hibernate:
      ddl-auto: update
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        exclude: env,beans
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    shutdown:
      enabled: true
