spring:
  datasource:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leanengine?setUnicode=true&characterEncoding=utf8
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        exclude: env,beans
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    shutdown:
      enabled: true
