@startuml

interface WorkflowTrigger{
  void execute(WorkflowContext);
}


WorkflowTrigger <|.. CommandJobTrigger
WorkflowTrigger <|.. CronJobTrigger
WorkflowTrigger <|.. ComponentEventTrigger
WorkflowTrigger <|.. ComponentStatusTrigger

WorkflowTrigger *-->  WorkflowInstanceScheduler

Class WorkflowRuntimeEngine

Class WorkflowInstanceScheduler

WorkflowRuntimeEngine *--> WorkflowInstanceScheduler
WorkflowRuntimeEngine *-> Job

WorkflowInstanceScheduler *--> WorkflowInstance

Class WorkflowInstance{
    InstanceStatus status
    LocalDateTime startupTime;
    LocalDateTime lastRunTime;
    LocalDateTime endTime;
    Component lastRunComponent;
    WorkflowInstanceResult result;
}

WorkflowInstanceResult "1" *--> "[1..N]" ComponentResult
class ComponentResult{
    Sting name;
    Stirng componentPath;
    KeyValuePair data;
}

WorkflowInstance *--> Workflow

Abstract Class Activity{
    String name
    LocalDateTime startTime
    LocalDateTime endTime
    ActivityStatus status
}

Class WorkflowContext{
    ComponentResult read(componentPath)
    void write(componentPath, ComponentResult)
}

interface Job{
    void execute(WorflowContext)
}

Activity "1" *-->  "[1...*]" Job

Job *--> WorkflowContext
Job *--> WorkflowInstanceResult


@enduml