version: '3.7'
services:
  db:
    image: mysql:5.7
    tmpfs: /var/lib/mysql:rw
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=20M',
      '--character-set-server=utf8mb4',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1',
      '--max-connections=1000',
      '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
    ]
    environment:
      - "MYSQL_DATABASE=leanengine"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
      - "MYSQL_ROOT_PASSWORD="
    ports:
      - "3306:3306"
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: leanengine
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
#  redis:
#    image: redis:4.0.11
#    command: redis-server --appendonly no
#    ports:
#      - "6379:6379"
#
#  mock_server:
#    image: edisonhsu/moco:latest
#    volumes:
#      - ../src/test/resources/mockdata/:/moco/config/
#    ports:
#      - "12306:12306"