name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Google Java Format
      uses: axel-op/googlejavaformat-action@v2.0.0
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Gradle Build
      uses: eskatos/gradle-command-action@v1
      with:
        # Gradle version to use
        gradle-version: 5.6.2
        # Gradle command line arguments, see gradle --help
        arguments: clean build
